#!/bin/bash

# Script for the change of file names from a directory from upper to lower or vice versa

prepareFile() {
    FILE="$(basename "${entry}")"
    extension="${FILE##*.}"
    FILE="${FILE%.*}"
}

auto_flip_lower_upper() {
    #Logic for the character flip in file name to upper from lower or lower to upper
    cleanName=${FILE//[^[:alpha:]]/}
    if [[ $cleanName =~ ^[[:upper:]]+$ ]]; then
        newName=$(echo $FILE | tr '[:upper:]' '[:lower:]')
    elif [[ $cleanName =~ ^[[:lower:]]+$ ]]; then
        newName=$(echo $FILE | tr '[:lower:]' '[:upper:]')
    else
        newName=$(echo $FILE | tr '[:upper:]' '[:lower:]')
    fi
}

rename() {
    if [ -f "${DIR}/${FILE}" ]; then
        mv "${DIR}/${FILE}" "${DIR}/$newName"
    elif [ -f "${DIR}/${FILE}.${extension}" ]; then
        mv "${DIR}/${FILE}.${extension}" "${DIR}/$newName.${extension}"
    elif [ -d "${DIR}/${FILE}" ]; then
        $(./script_1 -d "${DIR}/${FILE}")
    fi
}

script_main() {
    DIR=$directory
    FILE=
    newName=
    extension=
    for entry in "$DIR"/*; do
        prepareFile
        auto_flip_lower_upper
        rename
    done
}

usage() {
    echo "usage: script_1 [[[-d directory ] [-i]] | [-h]]"
}

##### Main

interactive=
directory=$HOME

while [ "$1" != "" ]; do
    case $1 in
    -d | --directory)
        shift
        directory=$1
        ;;
    -i | --interactive)
        interactive=1
        ;;
    -h | --help)
        usage
        exit
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done

# Test code to verify command line processing

if [ "$interactive" = "1" ]; then

    response=

    read -p "Enter name of directory [$directory] > " response
    if [ -n "$response" ]; then
        directory="$response"
    fi

    if [ -f $directory ]; then
        echo -n "Output file exists. Overwrite? (y/n) > "
        read response
        if [ "$directory" != "y" ]; then
            echo "Exiting program."
            exit 1
        fi
    fi
fi

script_main
