#!/bin/bash

# My first script

read="dir1/TRAP"
DIR="$(dirname "${read}")"
FILE="$(basename "${read}")"

[[ $FILE =~ ^[[:upper:]]+$ ]] && echo "All upper case"
if [[ $FILE =~ ^[[:upper:]]+$ ]]; then
    rename=$(echo $FILE | tr '[:upper:]' '[:lower:]')
elif [[ $read =~ ^[[:lower:]]+$ ]]; then
    rename=$(echo $FILE | tr '[:lower:]' '[:upper:]')
else
    rename=$(echo $FILE | tr '[:lower:]' '[:upper:]')
fi

#rename=$(echo $read | tr '[:upper:]' '[:lower:]')
#rename=$(echo $read | tr '[:lower:]' '[:upper:]')
echo $read
mv "${DIR}/${FILE}" "${DIR}/$rename"
